import { Article, Author } from '@/types'

export const mockAuthors: Partial<Author>[] = [
  {
    id: 'author-1',
    name: 'Sophea Chan',
    slug: 'sophea-chan',
    role: 'Senior Political Correspondent',
    bio: 'Sophea Chan has covered politics for over 15 years, specializing in electoral systems and parliamentary affairs.',
    avatar: { id: 'media-a1', filename: 'sophea.jpg', url: 'https://picsum.photos/seed/sophea/200/200', alt: 'Sophea Chan' } as any,
    twitter: 'sophea_trend7',
    email: 'sophea@trend7news.com',
  },
  {
    id: 'author-2',
    name: 'Dara Pich',
    slug: 'dara-pich',
    role: 'International Affairs Editor',
    bio: 'Dara Pich leads Trend7News international desk, reporting on global diplomacy and geopolitics.',
    avatar: { id: 'media-a2', filename: 'dara.jpg', url: 'https://picsum.photos/seed/dara/200/200', alt: 'Dara Pich' } as any,
    twitter: 'dara_trend7',
    email: 'dara@trend7news.com',
  },
  {
    id: 'author-3',
    name: 'Maly Ros',
    slug: 'maly-ros',
    role: 'Data & Investigations Reporter',
    bio: 'Maly Ros leads data investigations, turning complex datasets into compelling public-interest stories.',
    avatar: { id: 'media-a3', filename: 'maly.jpg', url: 'https://picsum.photos/seed/maly/200/200', alt: 'Maly Ros' } as any,
    twitter: 'maly_trend7',
    email: 'maly@trend7news.com',
  },
]

const auth = (id: string) => mockAuthors.find((a) => a.id === id) as any

export const mockArticles: Partial<Article>[] = [
  {
    id: 'art-1',
    title: 'Parliament Votes to Extend Emergency Powers for Third Consecutive Year',
    slug: 'parliament-votes-extend-emergency-powers',
    excerpt: 'The lower house passed a resolution extending executive emergency powers by a margin of 87 votes, drawing fierce opposition from civil society groups.',
    coverImage: { url: 'https://images.unsplash.com/photo-1529107386311-07b54f597bb3?q=80&w=2000&auto=format&fit=crop', alt: 'Parliament building at night' } as any,
    author: auth('author-1'),
    status: 'published',
    isBreaking: true,
    isFeatured: true,
    language: 'all',
    publishedAt: '2026-04-12T04:00:00Z',
    readTime: 6,
    tags: [{ tag: 'parliament' }, { tag: 'emergency powers' }, { tag: 'legislation' }],
    createdAt: '2026-04-12T04:00:00Z',
    updatedAt: '2026-04-12T04:00:00Z',
  },
  {
    id: 'art-2',
    title: 'Opposition Leader Calls for Snap Election Amid Economic Crisis',
    slug: 'opposition-leader-calls-snap-election-economic-crisis',
    excerpt: 'In a strongly worded statement, the opposition leader demanded the government dissolve parliament and call for fresh elections within 90 days.',
    coverImage: { url: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?q=80&w=2000&auto=format&fit=crop', alt: 'Opposition rally with banners' } as any,
    author: auth('author-1'),
    status: 'published',
    isBreaking: true,
    isFeatured: true,
    publishedAt: '2026-04-11T10:00:00Z',
    readTime: 5,
    tags: [{ tag: 'elections' }, { tag: 'opposition' }, { tag: 'economy' }],
    createdAt: '2026-04-11T10:00:00Z',
    updatedAt: '2026-04-11T10:00:00Z',
  },
  {
    id: 'art-3',
    title: 'Foreign Minister Signs Historic Trade Deal with Regional Bloc',
    slug: 'foreign-minister-signs-historic-trade-deal-regional-bloc',
    excerpt: 'After 18 months of negotiations, the landmark agreement will eliminate tariffs on over 4,000 goods and open new corridors for regional investment.',
    coverImage: { url: 'https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?q=80&w=2000&auto=format&fit=crop', alt: 'ministers signing agreement' } as any,
    author: auth('author-2'),
    status: 'published',
    isBreaking: false,
    isFeatured: true,
    publishedAt: '2026-04-10T08:30:00Z',
    readTime: 7,
    tags: [{ tag: 'trade' }, { tag: 'ASEAN' }, { tag: 'international' }],
    createdAt: '2026-04-10T08:30:00Z',
    updatedAt: '2026-04-10T08:30:00Z',
  },
  {
    id: 'art-4',
    title: 'Supreme Court Rules Against Government in Landmark Privacy Case',
    slug: 'supreme-court-rules-against-government-landmark-privacy-case',
    excerpt: 'The court\'s 6-3 ruling found that mass surveillance programs violated constitutional privacy rights, ordering an immediate suspension of data collection.',
    coverImage: { url: 'https://images.unsplash.com/photo-1589216532372-1c2a11f90e6a?q=80&w=2000&auto=format&fit=crop', alt: 'Supreme court exterior' } as any,
    author: auth('author-1'),
    status: 'published',
    isBreaking: false,
    isFeatured: false,
    publishedAt: '2026-04-09T14:00:00Z',
    readTime: 8,
    tags: [{ tag: 'supreme court' }, { tag: 'privacy' }, { tag: 'ruling' }],
    createdAt: '2026-04-09T14:00:00Z',
    updatedAt: '2026-04-09T14:00:00Z',
  },
  {
    id: 'art-5',
    title: 'Global Tech Summit Announces Next-Generation AI Safety Standards',
    slug: 'global-tech-summit-announces-ai-safety-standards',
    excerpt: 'Leading artificial intelligence labs and international regulators have agreed on a unified framework for frontier model testing and alignment safety.',
    coverImage: { url: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=2000&auto=format&fit=crop', alt: 'AI robot and futuristic screen' } as any,
    author: auth('author-3'),
    status: 'published',
    isBreaking: true,
    isFeatured: true,
    publishedAt: '2026-04-08T16:20:00Z',
    readTime: 6,
    tags: [{ tag: 'technology' }, { tag: 'ai' }, { tag: 'safety' }],
    createdAt: '2026-04-08T16:20:00Z',
    updatedAt: '2026-04-08T16:20:00Z',
  },
  {
    id: 'art-6',
    title: 'Central Bank Hikes Interest Rates to Curb Inflationary Pressures',
    slug: 'central-bank-hikes-interest-rates-inflation',
    excerpt: 'Financial markets reacted sharply after the central monetary authority raised key lending rates by 50 basis points, citing persistent energy price shocks.',
    coverImage: { url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=2000&auto=format&fit=crop', alt: 'Stock market chart' } as any,
    author: auth('author-2'),
    status: 'published',
    isBreaking: false,
    isFeatured: false,
    publishedAt: '2026-04-07T09:15:00Z',
    readTime: 5,
    tags: [{ tag: 'economy' }, { tag: 'banking' }, { tag: 'inflation' }],
    createdAt: '2026-04-07T09:15:00Z',
    updatedAt: '2026-04-07T09:15:00Z',
  },
  {
    id: 'art-7',
    title: 'Renewable Energy Initiative Reaches Milestone 50% Grid Capacity',
    slug: 'renewable-energy-initiative-reaches-50-percent-grid',
    excerpt: 'Solar and wind infrastructure expansion has successfully reached half of total national power generation ahead of the 2030 climate action schedule.',
    coverImage: { url: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?q=80&w=2000&auto=format&fit=crop', alt: 'Wind turbines and solar panels' } as any,
    author: auth('author-3'),
    status: 'published',
    isBreaking: false,
    isFeatured: false,
    publishedAt: '2026-04-06T11:45:00Z',
    readTime: 4,
    tags: [{ tag: 'climate' }, { tag: 'energy' }, { tag: 'sustainability' }],
    createdAt: '2026-04-06T11:45:00Z',
    updatedAt: '2026-04-06T11:45:00Z',
  }
]
